version: 2

version: 2
mkdocs:
  # Path to your MkDocs configuration file.
  configuration: mkdocs.yml
  
python:
  install:
    - requirements: source/rtd_requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3"
