version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/.travis.yml
  
python:
  install:
    - requirements: source/rtd_requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3"
